name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'whatsapp-ai-bot-6fc86fd7'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/WhatsAppAIAssistantBot.Api/WhatsAppAIAssistantBot.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{env.DOTNET_ROOT}}/myapp

    - name: Wait for deployment
      run: sleep 30

    - name: Health Check
      run: |
        echo "Testing health endpoint..."
        response=$(curl -s -w "%{http_code}" -o /tmp/health_response.json "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health")
        
        if [ "$response" -eq 200 ]; then
          echo "Health check passed!"
          echo "Response:"
          cat /tmp/health_response.json
        else
          echo "Health check failed with status code: $response"
          exit 1
        fi

    - name: API Endpoint Test
      run: |
        echo "Testing WhatsApp API endpoint..."
        response=$(curl -s -w "%{http_code}" -o /dev/null -X GET "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/whatsapp")
        
        if [ "$response" -eq 405 ]; then
          echo "WhatsApp API endpoint test passed! (405 Method Not Allowed is expected for GET)"
        else
          echo "WhatsApp API endpoint test failed with status code: $response"
          exit 1
        fi